DEBUG_MODE = True

WSZ_VERSION = '1.0'
MAX_CONTENT_LENGTH_IN_MB = 560
UPLOAD_ZONE_PATH = 'UPLOADZONE'
DOWNLOAD_ZONE_PATH = 'DOWNLOADZONE'
SHAREZONE_ZONE_PATH = 'SHAREZONE'
CAN_SIGNUP = True

class Config:
    SQLALCHEMY_DATABASE_URI = 'sqlite:///' + 'database.db'
    SECRET_KEY = 'ABC_123_CBA_321'
    SQLALCHEMY_TRACK_MODIFICATIONS = True
    MAX_CONTENT_LENGTH = MAX_CONTENT_LENGTH_IN_MB * 1024 * 1024
